version: '3.7'

services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - 'pushgateway'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - 'pushgateway'
      - 'prometheus'